import vazirFont from "@/constants/localFonts";
import '../globals.css'
import Header from "@/pages/Header";
import {Toaster} from "react-hot-toast";
import Provider from "@/pages/Provider";


export const metadata = {
    title: 'next shop panel', description: 'Generated by ali bahrampoor',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" dir={'rtl'}>
        <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>
        <Provider>
            <Header/>
            <div className="container xl:max-w-screen-xl">

                {children}

            </div>
            <Toaster/>
        </Provider>
        </body>
        </html>
    )
}
